"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import msg.arx5_state_t

import msg.arx5_gain_t

class arx5_response_t(object):
    __slots__ = ["resp_type", "state", "gain", "error_msg"]

    TYPE_STATE = 1
    TYPE_GAIN = 2
    TYPE_OK = 3
    TYPE_ERROR = 4

    def __init__(self):
        self.resp_type = 0
        self.state = msg.arx5_state_t()
        self.gain = msg.arx5_gain_t()
        self.error_msg = ""

    def encode(self):
        buf = BytesIO()
        buf.write(arx5_response_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.resp_type))
        assert self.state._get_packed_fingerprint() == msg.arx5_state_t._get_packed_fingerprint()
        self.state._encode_one(buf)
        assert self.gain._get_packed_fingerprint() == msg.arx5_gain_t._get_packed_fingerprint()
        self.gain._encode_one(buf)
        __error_msg_encoded = self.error_msg.encode('utf-8')
        buf.write(struct.pack('>I', len(__error_msg_encoded)+1))
        buf.write(__error_msg_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != arx5_response_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return arx5_response_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = arx5_response_t()
        self.resp_type = struct.unpack(">i", buf.read(4))[0]
        self.state = msg.arx5_state_t._decode_one(buf)
        self.gain = msg.arx5_gain_t._decode_one(buf)
        __error_msg_len = struct.unpack('>I', buf.read(4))[0]
        self.error_msg = buf.read(__error_msg_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if arx5_response_t in parents: return 0
        newparents = parents + [arx5_response_t]
        tmphash = (0x4e360d7c78fa639d+ msg.arx5_state_t._get_hash_recursive(newparents)+ msg.arx5_gain_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if arx5_response_t._packed_fingerprint is None:
            arx5_response_t._packed_fingerprint = struct.pack(">Q", arx5_response_t._get_hash_recursive([]))
        return arx5_response_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

