"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class arx5_gain_t(object):
    __slots__ = ["num_joints", "kp", "kd", "gripper_kp", "gripper_kd"]

    def __init__(self):
        self.num_joints = 0
        self.kp = []
        self.kd = []
        self.gripper_kp = 0.0
        self.gripper_kd = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(arx5_gain_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.num_joints))
        buf.write(struct.pack('>%dd' % self.num_joints, *self.kp[:self.num_joints]))
        buf.write(struct.pack('>%dd' % self.num_joints, *self.kd[:self.num_joints]))
        buf.write(struct.pack(">dd", self.gripper_kp, self.gripper_kd))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != arx5_gain_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return arx5_gain_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = arx5_gain_t()
        self.num_joints = struct.unpack(">i", buf.read(4))[0]
        self.kp = struct.unpack('>%dd' % self.num_joints, buf.read(self.num_joints * 8))
        self.kd = struct.unpack('>%dd' % self.num_joints, buf.read(self.num_joints * 8))
        self.gripper_kp, self.gripper_kd = struct.unpack(">dd", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if arx5_gain_t in parents: return 0
        tmphash = (0x722017fa886135f1) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if arx5_gain_t._packed_fingerprint is None:
            arx5_gain_t._packed_fingerprint = struct.pack(">Q", arx5_gain_t._get_hash_recursive([]))
        return arx5_gain_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

