"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class arx5_joint_command_t(object):
    __slots__ = ["cmd_type", "preview_time", "num_joints", "joint_pos", "gripper_pos"]

    CMD_GET_STATE = 1
    CMD_SET_JOINT_CMD = 2
    CMD_RESET_TO_HOME = 3
    CMD_SET_TO_DAMPING = 4

    def __init__(self):
        self.cmd_type = 0
        self.preview_time = 0.0
        self.num_joints = 0
        self.joint_pos = []
        self.gripper_pos = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(arx5_joint_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">idi", self.cmd_type, self.preview_time, self.num_joints))
        buf.write(struct.pack('>%dd' % self.num_joints, *self.joint_pos[:self.num_joints]))
        buf.write(struct.pack(">d", self.gripper_pos))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != arx5_joint_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return arx5_joint_command_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = arx5_joint_command_t()
        self.cmd_type, self.preview_time, self.num_joints = struct.unpack(">idi", buf.read(16))
        self.joint_pos = struct.unpack('>%dd' % self.num_joints, buf.read(self.num_joints * 8))
        self.gripper_pos = struct.unpack(">d", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if arx5_joint_command_t in parents: return 0
        tmphash = (0x55a7a078f27975d9) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if arx5_joint_command_t._packed_fingerprint is None:
            arx5_joint_command_t._packed_fingerprint = struct.pack(">Q", arx5_joint_command_t._get_hash_recursive([]))
        return arx5_joint_command_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

