"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import msg.arx5_gain_t

class arx5_command_t(object):
    __slots__ = ["cmd_type", "ee_pose", "gripper_pos", "preview_time", "gain"]

    CMD_GET_STATE = 1
    CMD_SET_EE_POSE = 2
    CMD_RESET_TO_HOME = 3
    CMD_SET_TO_DAMPING = 4
    CMD_GET_GAIN = 5
    CMD_SET_GAIN = 6

    def __init__(self):
        self.cmd_type = 0
        self.ee_pose = [ 0.0 for dim0 in range(6) ]
        self.gripper_pos = 0.0
        self.preview_time = 0.0
        self.gain = msg.arx5_gain_t()

    def encode(self):
        buf = BytesIO()
        buf.write(arx5_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.cmd_type))
        buf.write(struct.pack('>6d', *self.ee_pose[:6]))
        buf.write(struct.pack(">dd", self.gripper_pos, self.preview_time))
        assert self.gain._get_packed_fingerprint() == msg.arx5_gain_t._get_packed_fingerprint()
        self.gain._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != arx5_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return arx5_command_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = arx5_command_t()
        self.cmd_type = struct.unpack(">i", buf.read(4))[0]
        self.ee_pose = struct.unpack('>6d', buf.read(48))
        self.gripper_pos, self.preview_time = struct.unpack(">dd", buf.read(16))
        self.gain = msg.arx5_gain_t._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if arx5_command_t in parents: return 0
        newparents = parents + [arx5_command_t]
        tmphash = (0x66ee07442626c60+ msg.arx5_gain_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if arx5_command_t._packed_fingerprint is None:
            arx5_command_t._packed_fingerprint = struct.pack(">Q", arx5_command_t._get_hash_recursive([]))
        return arx5_command_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

