"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class arx5_state_t(object):
    __slots__ = ["timestamp", "num_joints", "joint_pos", "joint_vel", "joint_torque", "ee_pose", "gripper_pos", "gripper_vel", "gripper_torque"]

    def __init__(self):
        self.timestamp = 0.0
        self.num_joints = 0
        self.joint_pos = []
        self.joint_vel = []
        self.joint_torque = []
        self.ee_pose = [ 0.0 for dim0 in range(6) ]
        self.gripper_pos = 0.0
        self.gripper_vel = 0.0
        self.gripper_torque = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(arx5_state_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">di", self.timestamp, self.num_joints))
        buf.write(struct.pack('>%dd' % self.num_joints, *self.joint_pos[:self.num_joints]))
        buf.write(struct.pack('>%dd' % self.num_joints, *self.joint_vel[:self.num_joints]))
        buf.write(struct.pack('>%dd' % self.num_joints, *self.joint_torque[:self.num_joints]))
        buf.write(struct.pack('>6d', *self.ee_pose[:6]))
        buf.write(struct.pack(">ddd", self.gripper_pos, self.gripper_vel, self.gripper_torque))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != arx5_state_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return arx5_state_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = arx5_state_t()
        self.timestamp, self.num_joints = struct.unpack(">di", buf.read(12))
        self.joint_pos = struct.unpack('>%dd' % self.num_joints, buf.read(self.num_joints * 8))
        self.joint_vel = struct.unpack('>%dd' % self.num_joints, buf.read(self.num_joints * 8))
        self.joint_torque = struct.unpack('>%dd' % self.num_joints, buf.read(self.num_joints * 8))
        self.ee_pose = struct.unpack('>6d', buf.read(48))
        self.gripper_pos, self.gripper_vel, self.gripper_torque = struct.unpack(">ddd", buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if arx5_state_t in parents: return 0
        tmphash = (0xd8ad7f7ed61cb79c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if arx5_state_t._packed_fingerprint is None:
            arx5_state_t._packed_fingerprint = struct.pack(">Q", arx5_state_t._get_hash_recursive([]))
        return arx5_state_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

