"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class TaskGroupData(object):
    __slots__ = ["task_group"]

    __typenames__ = ["string"]

    __dimensions__ = [None]

    def __init__(self):
        self.task_group = ""

    def encode(self):
        buf = BytesIO()
        buf.write(TaskGroupData._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __task_group_encoded = self.task_group.encode('utf-8')
        buf.write(struct.pack('>I', len(__task_group_encoded)+1))
        buf.write(__task_group_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != TaskGroupData._get_packed_fingerprint():
            raise ValueError("Decode error")
        return TaskGroupData._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = TaskGroupData()
        __task_group_len = struct.unpack('>I', buf.read(4))[0]
        self.task_group = buf.read(__task_group_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if TaskGroupData in parents: return 0
        tmphash = (0xed6d1d4a2e89aa65) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if TaskGroupData._packed_fingerprint is None:
            TaskGroupData._packed_fingerprint = struct.pack(">Q", TaskGroupData._get_hash_recursive([]))
        return TaskGroupData._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", TaskGroupData._get_packed_fingerprint())[0]

